import { type Enchantment, world } from "@minecraft/server";
import { ModalFormData, type ModalFormResponse } from "@minecraft/server-ui";
import type { GivexJson } from "../../commands/utils/json";
import { safeModalFormShow } from "../safeShow";
import { commandVector3ToString } from "./commandVector3";
import { type GetStartedContext, getStartedTitle } from "./getStarted";

function enchantsToList(enchants: Enchantment[]): string {
	let list: string = "[";
	for (const enchant of enchants) {
		list += `\\"${enchant.type.id}\\",`;
		if (enchant.level > 1) {
			list += `${enchant.level},`;
		}
	}
	list = `${list.slice(0, list.length - 1)}]`;
	return list;
}

function contextToCommand(context: GetStartedContext): string {
	const j: GivexJson = context.json;
	let str: string = "";
	if (context.commandType === "givex") {
		str = `/givex @p ${j.typeId} "{\\"amount\\":${j.amount},`;
	} else {
		str = `/${context.commandType} ${commandVector3ToString(context.location)} ${j.typeId} "{\\"amount\\":${j.amount},`;
	}
	if (j.nameTag !== null) {
		str += `\\"nameTag\\":\\"${j.nameTag}\\",`;
	}
	if (j.data !== null) {
		str += `\\"data\\":${j.data},`;
	}
	if (j.lockMode !== null) {
		str += `\\"lockMode\\":\\"${j.lockMode}\\",`;
	}
	if (j.keepOnDeath !== null) {
		str += `\\"keepOnDeath\\":${j.keepOnDeath},`;
	}
	if (j.canPlaceOn !== null) {
		str += `\\"canPlaceOn\\":[\\"${j.canPlaceOn.join('\\",\\"')}\\"],`;
	}
	if (j.canDestroy !== null) {
		str += `\\"canDestroy\\":[\\"${j.canDestroy.join('\\",\\"')}\\"],`;
	}
	if (j.durability !== null) {
		if (j.durability === "unbreakable") {
			str += `\\"durability\\":\\"unbreakable\\",`;
		} else {
			str += `\\"durability\\":${j.durability},`;
		}
	}
	if (context.enchants.length > 0) {
		str += `\\"enchants\\":${enchantsToList(context.enchants)},`;
	}
	if (j.slot !== null) {
		str += `\\"slot\\":\\"${j.slot}\\",`;
	}
	if (j.slotId !== null) {
		str += `\\"slotId\\":${j.slotId},`;
	}
	if (j.replaceMode !== null && j.replaceMode !== "destroy") {
		// destroy is default
		str += `\\"replaceMode\\":\\"${j.replaceMode}\\",`;
	}
	str = `${str.slice(0, str.length - 1)}}"`;
	return str;
}

export async function getStartedSubmit(context: GetStartedContext): Promise<void> {
	const form = new ModalFormData();
	form.title(getStartedTitle);
	const command: string = contextToCommand(context);
	form.textField("\nCopy generated command below:", "", { defaultValue: command });
	form.divider();
	form.toggle("Share command in chat?", { defaultValue: false });
	form.submitButton("Done");
	const resp: ModalFormResponse = await safeModalFormShow(form, context.player);
	if (resp.formValues?.[2]) {
		world.sendMessage(`§7Command generated by ${context.player.name}:§r\n${command}`);
	}
}
